#!/bin/sh
set -ev
sudo apt-get install -y --force-yes openjdk-7-jre-headless
sudo cp lein /usr/bin
sudo -u ubuntu bash -c "lein new compojure-app my-app"
cd my-app
sudo -u ubuntu bash -c "nohup lein ring server > /home/ubuntu/server.log &"
open-port 3000
