#!/bin/sh
set -ev
sudo apt-get install -y --force-yes openjdk-7-jre-headless
sudo cp lein /usr/bin
sudo su -c "cd $HOME && lein new compojure-app my-app" ubuntu
sudo su -c "cd $HOME/my-app && lein ring server" ubuntu
open-port 3000
